language: python
python:
  - "2.7"
before_install:
  - "export DISPLAY=:99.0"
  - sudo apt-get update -qq
  - sudo apt-get install -y python-qt4 python-qt4-gl python-box2d
  - "sh -e /etc/init.d/xvfb start"
script:
  - python -m unittest discover pilasengine/tests '*.py'
virtualenv:
  system_site_packages: true
