safe: true
lsi: false
pygments: true
markdown: redcarpet

navigation:
- text: Home
  url: /index.html
- text: Blog
  url: /blog.html
- text: Comunidad
  url: /foro.html
- text: Imágenes
  url: /galeria.html
- text: Videos
  url: /videos.html
- text: Documentación
  url: /docs.html
- text: Descargas
  url: /descargas.html
- text: Doná
  url: /donaciones.html
